### ISSUE TITLE
train SSD error.

### ISSUE THREAD

**Issue by panecho** [jinfagang/TrafficLightsDetection#10]
when I run `python train_ssd_lisa.py` the error:
`Cannot copy param 0 weights from layer 'fc6'; shape mismatch.  Source param shape is 1 1 4096 25088 (102760448); target param shape is 1024 512 3 3 (4718592). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.`

any idea to make it work quickly? but the way, my input image size is 960*544.

**Comment by whw12345** [comment]
Traceback (most recent call last):
  File "train_ssd_lisa.py", line 457, in <module>
    prior_variance=prior_variance, kernel_size=3, pad=1,lr_mult=lr_mult,conf_postfix='lisa')
  File "/home/gwm/caffe_ssd/python/caffe/model_libs.py", line 870, in CreateMultiBoxHead
    num_output=num_loc_output, kernel_size=kernel_size, pad=pad, stride=1, **bn_param)
  File "/home/gwm/caffe_ssd/python/caffe/model_libs.py", line 97, in ConvBNLayer
    net[conv_name] = L.Convolution(net[from_layer], num_output=num_output,
  File "/home/gwm/caffe_ssd/python/caffe/net_spec.py", line 188, in __getitem__
    return self.__getattr__(item)
  File "/home/gwm/caffe_ssd/python/caffe/net_spec.py", line 182, in __getattr__
    return self.tops[name]
KeyError: 'fc7_conv'

'fc7_conv'layer has some problems。

**Comment by lucasjinreal** [comment]
@whw12345  This repo were to old and deprecated, look around here to find more advanced faster and accurate methods: http://codes.strangeai.pro

**Comment by xiongcaihua** [comment]
> Traceback (most recent call last):
> File "train_ssd_lisa.py", line 457, in 
> prior_variance=prior_variance, kernel_size=3, pad=1,lr_mult=lr_mult,conf_postfix='lisa')
> File "/home/gwm/caffe_ssd/python/caffe/model_libs.py", line 870, in CreateMultiBoxHead
> num_output=num_loc_output, kernel_size=kernel_size, pad=pad, stride=1, **bn_param)
> File "/home/gwm/caffe_ssd/python/caffe/model_libs.py", line 97, in ConvBNLayer
> net[conv_name] = L.Convolution(net[from_layer], num_output=num_output,
> File "/home/gwm/caffe_ssd/python/caffe/net_spec.py", line 188, in **getitem**
> return self.**getattr**(item)
> File "/home/gwm/caffe_ssd/python/caffe/net_spec.py", line 182, in **getattr**
> return self.tops[name]
> KeyError: 'fc7_conv'
> 
> 'fc7_conv'layer has some problems。

I met the same issues, did you solved it?

**Comment by lucasjinreal** [comment]
@xiongcaihua  More recent and accurate traffic light detection examples can be found here: manaai.cn
